/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js in a standard project, and we keep it in source control
// so the initial scaffold is self-contained.

